Repository Chandan-devs-tech/drive-easy-backend, pull requests merged in 2023-11, with the labels that each got.

#13 Authentication
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/users_controller.rb
  app/controllers/application_controller.rb
  app/helpers/api/v1/users_helper.rb
  app/models/user.rb
  config/database.yml
  config/environments/development.rb
  config/initializers/cors.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20231111133359_create_users.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/api/v1/users_controller_test.rb
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: Authentication

#14 Car's Model and Controller
  app/controllers/api/v1/cars_controller.rb
  app/helpers/api/v1/cars_helper.rb
  app/models/car.rb
  app/models/user.rb
  config/database.yml
  config/routes.rb
  db/migrate/20231113194416_create_cars.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/api/v1/cars_controller_test.rb
  test/fixtures/cars.yml
  test/models/car_test.rb
Labels: Chandan's Task

#16 Update reservations_controller.rb
  app/controllers/api/v1/reservations_controller.rb
Labels: Cephas's Task

#17 API Doc and Unit Test
  .rspec
  Gemfile
  Gemfile.lock
  app/models/car.rb
  app/models/user.rb
  config/database.yml
  config/initializers/rswag_api.rb
  config/initializers/rswag_ui.rb
  config/routes.rb
  db/seeds.rb
  spec/models/car_spec.rb
  spec/models/reservation_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  swagger/v1/swagger.yaml
Labels: Chandan's Task
